// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseBfkFile() {
  return window['go']['main']['App']['BrowseBfkFile']();
}

export function DestroyAllCharacters() {
  return window['go']['main']['App']['DestroyAllCharacters']();
}

export function DestroyCharacter(arg1) {
  return window['go']['main']['App']['DestroyCharacter'](arg1);
}

export function GetActiveWindows() {
  return window['go']['main']['App']['GetActiveWindows']();
}

export function GetBfkPackInfo(arg1) {
  return window['go']['main']['App']['GetBfkPackInfo'](arg1);
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetFramesPath() {
  return window['go']['main']['App']['GetFramesPath']();
}

export function GetPreviewFrames(arg1, arg2) {
  return window['go']['main']['App']['GetPreviewFrames'](arg1, arg2);
}

export function GetPreviewImageBase64(arg1) {
  return window['go']['main']['App']['GetPreviewImageBase64'](arg1);
}

export function InstallBfkPack(arg1) {
  return window['go']['main']['App']['InstallBfkPack'](arg1);
}

export function OpenConfig() {
  return window['go']['main']['App']['OpenConfig']();
}

export function OpenFramesDir() {
  return window['go']['main']['App']['OpenFramesDir']();
}

export function SetCharacterScale(arg1, arg2) {
  return window['go']['main']['App']['SetCharacterScale'](arg1, arg2);
}

export function SpawnCharacter(arg1) {
  return window['go']['main']['App']['SpawnCharacter'](arg1);
}
