// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {PackManagement} from '../models';
import {AnimationEngine} from '../models';

export function BrowseBfkFile():Promise<string>;

export function DestroyAllCharacters():Promise<void>;

export function DestroyCharacter(arg1:string):Promise<boolean>;

export function GetActiveWindows():Promise<Array<main.CharacterWindowInfo>>;

export function GetBfkPackInfo(arg1:string):Promise<PackManagement.PackInfo>;

export function GetCharacters():Promise<Array<AnimationEngine.CharacterInfo>>;

export function GetConfigPath():Promise<string>;

export function GetFramesPath():Promise<string>;

export function GetPreviewFrames(arg1:string,arg2:number):Promise<Array<string>>;

export function GetPreviewImageBase64(arg1:string):Promise<string>;

export function InstallBfkPack(arg1:string):Promise<void>;

export function OpenConfig():Promise<void>;

export function OpenFramesDir():Promise<void>;

export function SetCharacterScale(arg1:string,arg2:number):Promise<boolean>;

export function SpawnCharacter(arg1:string):Promise<main.CharacterWindowInfo>;
