// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DestroyAllCharacters() {
  return window['go']['main']['App']['DestroyAllCharacters']();
}

export function DestroyCharacter(arg1) {
  return window['go']['main']['App']['DestroyCharacter'](arg1);
}

export function GetActiveWindows() {
  return window['go']['main']['App']['GetActiveWindows']();
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetPreviewImageBase64(arg1) {
  return window['go']['main']['App']['GetPreviewImageBase64'](arg1);
}

export function SetCharacterScale(arg1, arg2) {
  return window['go']['main']['App']['SetCharacterScale'](arg1, arg2);
}

export function SpawnCharacter(arg1) {
  return window['go']['main']['App']['SpawnCharacter'](arg1);
}
